name: Python Tests

on: [push,workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Debugging - List files
      run: ls -l

    - name: Debugging - Print content of test.py
      run: cat test.py

    - name: Run tests
      run: |
        echo "Running the test"
        python test.py

    - name: Lets see the output
      run: echo "$(python test.py)"
